trigger:
  branches:
    include:
      - master

pool:
  name: default

steps:   
- task: DotNetCoreCLI@2
  displayName: restore packages
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  
    
- task: DeleteFiles@1
  displayName: delete old packages
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'
    
- task: CopyFiles@2
  displayName: copy nwrfcsdk
  inputs: 
    sourceFolder: \\dfs\Development\Packages\nwrfcsdk
    targetFolder: $(Build.SourcesDirectory)\nwrfcsdk
    cleanTargetFolder: true
    
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    
# x86 platform builds
- task: MSBuild@1
  displayName: x86 platform builds
  inputs:
    platform: x86
    configuration: Release
   
# x64 platform builds
- task: MSBuild@1
  displayName: x64 platform builds
  inputs:
    platform: x64
    configuration: Release
    
# cleanup packages created in platform builds
- task: DeleteFiles@1
  displayName: cleanup packages created in platform builds
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'

# final build
- task: VSBuild@1
  inputs:
    platform: 'Any CPU'
    configuration: Release   

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --disable-parallel --no-build'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: build-packages

- task: NuGetCommand@2
  displayName: publish to project nuget repo
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '59a3608a-9bed-4cb4-9467-6efaaa3cbef5/1e425ef4-e3a0-4927-b4c0-2beff753cb88'  