trigger:
- master

pool:
  name: 'default'

steps:   
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  
    
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'
    
- task: CopyFiles@2
  inputs: 
    sourceFolder: \\dfs\Development\Packages\nwrfcsdk
    targetFolder: $(Build.SourcesDirectory)\nwrfcsdk
    cleanTargetFolder: true
    
- task: GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true
    
# x86 platform builds
- task: VSBuild@1
  inputs:
    platform: x86
    msbuildArgs: -ignoreprojectextensions:csproj
    configuration: Release
   
# x64 platform builds
- task: VSBuild@1
  inputs:
    platform: x64
    msbuildArgs: -ignoreprojectextensions:csproj
    configuration: Release 
    
# cleanup packages created in platform builds
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'

# final build
- task: VSBuild@1
  inputs:
    platform: 'Any CPU'
    configuration: Release   

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: build-packages
