trigger:
  branches:
    include:
      - master
      - refs/tags/v*

pool:
  vmImage: windows-latest  

steps:   
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  
    
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'
    
- task: CopyFiles@2
  inputs: 
    sourceFolder: \\dfs\Development\Packages\nwrfcsdk
    targetFolder: $(Build.SourcesDirectory)\nwrfcsdk
    cleanTargetFolder: true
    
- task: GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true
    
# x86 platform builds
- task: VSBuild@1
  inputs:
    platform: x86
    msbuildArgs: -ignoreprojectextensions:csproj
    configuration: Release
   
# x64 platform builds
- task: VSBuild@1
  inputs:
    platform: x64
    msbuildArgs: -ignoreprojectextensions:csproj
    configuration: Release 
    
# cleanup packages created in platform builds
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    contents: '**'

# final build
- task: VSBuild@1
  inputs:
    platform: 'Any CPU'
    configuration: Release   

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\build-packages
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: build-packages

- task: NuGetCommand@2
  displayName: publish to project nuget repo
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '59a3608a-9bed-4cb4-9467-6efaaa3cbef5/1e425ef4-e3a0-4927-b4c0-2beff753cb88'  